// <auto-generated />
using System;
using CollectorApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollectorApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollectorApp.Core.Entities.Organization", b =>
                {
                    b.Property<int>("SN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SN"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("Active");

                    b.Property<string>("DBName")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("DBName");

                    b.Property<string>("DBPassword")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("DBPassword");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("Date");

                    b.Property<string>("DbUser")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("DbUser");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(45)")
                        .HasColumnName("Email");

                    b.Property<string>("Mobile")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Mobile");

                    b.Property<string>("OrgCode")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("OrgCode");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("OrgName");

                    b.Property<string>("OrgPassword")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("OrgPassword");

                    b.Property<string>("Palika")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Palika");

                    b.Property<int?>("Qty")
                        .HasColumnType("int")
                        .HasColumnName("Qty");

                    b.Property<string>("TelNo")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TelNo");

                    b.Property<int?>("WardNo")
                        .HasColumnType("int")
                        .HasColumnName("WardNo");

                    b.HasKey("SN");

                    b.ToTable("CollectionApp", (string)null);
                });

            modelBuilder.Entity("CollectorApp.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Password");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("CollectionAppUser", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
